Repository prgrms-web-devcourse/FEDC5_React-Weather, pull requests merged in 2023-12, with the labels that each got.

#2 git husky 설정 적용
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
  public/index.html
  src/pages/Main.tsx
  tsconfig.json
Labels: setting

#4 useModal hook 및 modal Component 생성
  src/App.tsx
  src/Components/Common/Modal/index.scss
  src/Components/Common/Modal/index.tsx
  src/Types/Modal.ts
  src/common/Header.tsx
  src/common/index.ts
  src/hooks/useModal.tsx
  src/pages/Main.tsx
Labels: feat

#5 최익 working
  public/index.html
  src/App.scss
  src/App.tsx
  src/Components/Common/Icon.tsx
  src/Components/Main/Header/index.scss
  src/Components/Main/Header/index.tsx
  src/Components/Main/Search/index.scss
  src/Components/Main/Search/index.tsx
  src/Components/Main/Temperature/index.scss
  src/Components/Main/Temperature/index.tsx
  src/Components/Main/VeryShortTermForecast/Inner.tsx
  src/Components/Main/VeryShortTermForecast/index.scss
  src/Components/Main/VeryShortTermForecast/index.tsx
  src/Components/Main/index.scss
  src/Components/Main/index.tsx
  src/Images/cloudy.png
  src/Images/gale.png
  src/Images/index.ts
  src/Images/rain.png
  src/Images/sun.png
  src/Images/temperature.png
  src/Routes/Main.tsx
  src/Types/Icon.ts
  src/Types/Inner.ts
  src/Types/Temperature.ts
Labels: fix

#6 searchBar & searchList UI 구현 및 반응형 적용
  src/App.scss
  src/App.tsx
  src/Components/Main/Search/index.scss
  src/Components/Main/Search/index.tsx
  src/Components/Main/VeryShortTermForecast/index.scss
  src/Components/SearchModal/SearchBar/index.scss
  src/Components/SearchModal/SearchBar/index.tsx
  src/Components/SearchModal/SearchList/index.scss
  src/Components/SearchModal/SearchList/index.tsx
  src/Components/SearchModal/index.tsx
  src/Images/searchIcon.svg
  src/Routes/Main.tsx
  src/Types/Modal.ts
  src/style/_reset.scss
  src/style/_responsive.scss
  src/style/index.scss
Labels: feat

#7 대기질 컴포넌트 UI 구현 & 현재 위치 조회 & Kakao MAP API로 주소 출력하기
  api/kakaoAPI.ts
  package.json
  src/App.scss
  src/Components/Main/AirQuality/index.scss
  src/Components/Main/AirQuality/index.tsx
  src/Types/Geolocation.ts
  src/hooks/useGeoCoding.tsx
  src/hooks/useGeolocation.tsx
  src/style/index.scss
Labels: feat

#8 중기예보 컴포넌트 UI구현
  .eslintrc.json
  .husky/pre-commit
  src/App.scss
  src/Components/Main/MediumTermForecast/MediumTermForecastItem.tsx
  src/Components/Main/MediumTermForecast/index.scss
  src/Components/Main/MediumTermForecast/index.tsx
  src/Components/Main/index.tsx
  src/Types/mediumTermForecast.ts
  src/hooks/useGetWidth.tsx
Labels: feat
